### ISSUE TITLE
avoid hardcoding -i for ffmpeg

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#24]
ATM `-i hw:0 ` is used on linux and would need to be ` -i "0:1"` on mac.  Moreover there could be multiple usb devices attached and it would not necessarily be `0`.  The easiest quick way forward is to make it configurable from command line, so could probably be done along with #23 .

In the longer run, if we stay with ffmpeg and not switch to use magewel API, we should auto-detect which usb port to use by matching the name of the device or device id, as e.g. could be queried via `lsusb` from command line (in program, should just use a function from libusb or alike)

**Comment by andycon** [comment]
The options for FFmpeg are written in <PATHTO>/reprostim/Capture/C++/config.yaml
There is no command-line option and no auto-detect.

So the user can (atm) edit the config file to the appropriate setting.  However, the path to the config file (which is atm hardcoded) should be in a sensible place, because it gets read relative to the location of the compiled cpp code. So at first I had it designated in the VideoCapture.cpp code as something like: yaml-read("config.yaml"), but when I moved the compiled executable VideoCapture to the location from which the service runs it (i.e., /usr/sbin/VideoCapture), the program failed. So, for the moment, I hardcoded the entire path as : "/home/andy/reprostim/Capture/C++/config.yaml".  Perhaps this should be in /etc/reprostim/config.yaml. ??

Such would make sense if a setup/install script would create the /etc/reprostim folder, with all appropriate stuff in there...

**Comment by yarikoptic** [comment]
> There is no command-line option and no auto-detect.

There should be a command line option for starters.

>  Perhaps this should be in /etc/reprostim/config.yaml. ??

we can leave that to the distribution.  Users might not be able to install system wide (I do not think it is strictly required iirc) and might need to keep it under e.g. ~/.config/reprostim/config.yaml .  If it was python  we could easily get through expected (system-wide and user-wider) directories to check for the file.  But I would not bother about that for now.  Just add/use a command line option to point to the specific config.yaml file.

**Comment by andycon** [comment]
ok. I added command line opts for where "reprostim_home" directory, config.yaml path, and video save directory. To simplify things, its possible to specify just the home directory, causing the program to look into the home directory for ~/Videos, and for ~/config.yaml.

will next (1) add option to choose input device (e.g., /dev/video0), which will also be optional, where if its not specified on command line, the program then looks in the config.yaml for config.

then (2) will add an auto-detect functionality.

andy@reproiner:~/reprostim/Capture/C++$ ./VideoCapture 
usage: ./VideoCapture -d <path> [-o <path> | -h ]
	-d <path>	REPROSTIM_HOME directory (not optional)
	-o <path>	Output directory where to save recordings (optional)
		Defaults to $REPROSTIM_HOME/Videos
	-c </path/to/config.yaml>	Path to configuration file (optional)
		Defaults to $REPROSTIM_HOME/config.yaml
	-h		Print this help string

**Comment by yarikoptic** [comment]
this was addressed AFAIK
