### ISSUE TITLE
ReproEvents: connect IO channel for button 5

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reprostim#54]
PYKA controller has 5 buttons. But we seems to record only 4 (1-4). See the log `2023-09-05T11:52:54-04:00.csv`.

**Comment by TheChymera** [comment]
Yes, we set it up for 4 since Terry said that's basically the only one that's used. In order to set up the fifth button I need to attach another jumper cable, and would need to know which cable channel the fifth button goes through.

I recorded the information from the documentation [here](https://github.com/ReproNim/reprostim/blob/master/Events/connector_cable.csv), and it *looks* like button 5 is cable channel 22, I would however need to test that.

**Comment by yarikoptic** [comment]
this is done, and should be closed, correct?

**Comment by TheChymera** [comment]
Yes, this is now implemented on both device types.
